name: Create Issues from CSV

on:
  push:
    paths:
      - 'test_sample_data.csv'
  workflow_dispatch:

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run CSV Issue Creator
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python csv_issue_creator.py test_sample_data.csv

      - name: Commit processed IDs file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add processed_ids.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update processed Paper IDs [skip ci]"

      - name: Push changes
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git push https://x-access-token:${PERSONAL_TOKEN}@github.com/${{ github.repository }} HEAD:main
